[package]
name = "rgamesync"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
thiserror = "2.0.12"
rgamesync-rclone = { path = "rgamesync-rclone" }
rgamesync-config = { path = "rgamesync-config" }
anyhow = "1.0.98"
