blank_lines_upper_bound = 3
max_width = 120
fn_call_width = 100
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
